version: '3.7'

services:
  proxy:
    image: nginx:alpine
    container_name: proxy-izakaya
    ports:
      - '81:80'
    volumes:
      - ./api/nginx.conf:/etc/nginx/nginx.conf
    restart: 'unless-stopped'
    networks:
      - backend
  server:
    build:
      context: api
      target: development-build-stage
      dockerfile: Dockerfile
    container_name: server-izakaya
    ports:
      - '3001:3000'
    volumes:
      - ./api:/app
      - /app/node_modules
    restart: 'unless-stopped'
    networks:
      - backend
    links:
      - pg
    depends_on:
      - pg
  pg:
    image: bitnami/postgresql:11-debian-9
    container_name: pg-izakaya
    environment:
      POSTGRESQL_USERNAME: root
      POSTGRESQL_PASSWORD: password
      POSTGRESQL_DATABASE: dev
    ports:
      - '5434:5432'
    volumes:
      - izakaya-data:/bitnami/postgresql
    networks:
      - backend
  
  blog:
    build:
      context: blog
      target: development-build-stage
      dockerfile: Dockerfile
    container_name: blog-izakaya
    ports:
      - '8001:8000'
    volumes:
      - ./blog:/app
      - /app/node_modules
    restart: 'unless-stopped'

networks:
  backend:
    driver: bridge

volumes:
  data:
    driver: local
  izakaya-data:
    driver: local
